create table author (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), adress varchar(255) not null, name varchar(255) not null, url varchar(255) not null, primary key (id)) engine=InnoDB;
create table author_audit (id bigint not null, rev integer not null, revtype tinyint, adress varchar(255), name varchar(255), url varchar(255), primary key (id, rev)) engine=InnoDB;
create table book_audit (id bigint not null, rev integer not null, revtype tinyint, author_address varchar(255), author_name varchar(255), isbn varchar(20), price double precision, publisher_name varchar(255), title varchar(255), published_on mediumint, author_id bigint, publisher_id bigint, primary key (id, rev)) engine=InnoDB;
create table books (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), author_address varchar(255) not null, author_name varchar(255) not null, isbn varchar(20) not null, price double precision not null, publisher_name varchar(255) not null, title varchar(255) not null, published_on mediumint not null, author_id bigint not null, publisher_id bigint not null, primary key (id)) engine=InnoDB;
create table customer (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), email varchar(255), name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table customer_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), email varchar(255), name varchar(255), phone varchar(255), primary key (id, rev)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 75 );
create table publisher (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), adress varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, url varchar(255) not null, primary key (id)) engine=InnoDB;
create table publisher_audit (id bigint not null, rev integer not null, revtype tinyint, adress varchar(255), name varchar(255), phone varchar(255), url varchar(255), primary key (id, rev)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table shopping_basket (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), user_email varchar(255), customer_id bigint not null, primary key (id)) engine=InnoDB;
create table shopping_basket_audit (id bigint not null, rev integer not null, revtype tinyint, user_email varchar(255), customer_id bigint, primary key (id, rev)) engine=InnoDB;
create table shopping_basket_book (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), book_isbn varchar(255) not null, shopping_basket_id bigint not null, shopping_basket_book_id bigint not null, primary key (id)) engine=InnoDB;
create table shopping_basket_book_audit (id bigint not null, rev integer not null, revtype tinyint, book_isbn varchar(255), shopping_basket_id bigint, shopping_basket_book_id bigint, primary key (id, rev)) engine=InnoDB;
create table warehous (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), adress varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table warehouse_audit (id bigint not null, rev integer not null, revtype tinyint, adress varchar(255), phone varchar(255), primary key (id, rev)) engine=InnoDB;
create table warehouse_book (id bigint not null, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), book_isbn varchar(255) not null, warehouse_address varchar(255) not null, warehouse_id bigint not null, warehouse_book_id bigint not null, primary key (id)) engine=InnoDB;
create table warehouse_book_audit (id bigint not null, rev integer not null, revtype tinyint, book_isbn varchar(255), warehouse_address varchar(255), warehouse_id bigint, warehouse_book_id bigint, primary key (id, rev)) engine=InnoDB;
alter table books add constraint UK_kibbepcitr0a3cpk3rfr7nihn unique (isbn);
alter table author_audit add constraint FKp4vbplw134mimnk3nlxfvmch0 foreign key (rev) references revinfo (rev);
alter table book_audit add constraint FKjx5fxkthrd6kxbxb3ukwb04mf foreign key (rev) references revinfo (rev);
alter table books add constraint FKdh6rjf063y1kmud3t0vrmrlo3 foreign key (author_id) references author (id);
alter table books add constraint FK1eujqvebj0cej9mcivv49grwi foreign key (publisher_id) references publisher (id);
alter table customer_audit add constraint FKdt9qcovclyufwngwmdeywng89 foreign key (rev) references revinfo (rev);
alter table publisher_audit add constraint FKj7qitjv3h0lxkwmos2bfighst foreign key (rev) references revinfo (rev);
alter table shopping_basket add constraint FK9i2fkjr9skqwe7pb4btrtnke8 foreign key (customer_id) references customer (id);
alter table shopping_basket_audit add constraint FKonhk2sv5tm02hf2vpeh1h14l0 foreign key (rev) references revinfo (rev);
alter table shopping_basket_book add constraint FKh96esmuvxu50pr6lbcinyn077 foreign key (shopping_basket_id) references shopping_basket (id);
alter table shopping_basket_book add constraint FK6iyw22fa8o3tq6j2nuf8jmcvs foreign key (shopping_basket_book_id) references books (id);
alter table shopping_basket_book_audit add constraint FKh7i6ywxb9p7ks0hj76s0k3s1l foreign key (rev) references revinfo (rev);
alter table warehouse_audit add constraint FKlyyfpxiyr1hv0jnpbtoob3l1q foreign key (rev) references revinfo (rev);
alter table warehouse_book add constraint FKlclr60vjdgrtsboc8dq4et0uq foreign key (warehouse_id) references warehous (id);
alter table warehouse_book add constraint FKig4sxeovn1hfxpq714a7hrwox foreign key (warehouse_book_id) references books (id);
alter table warehouse_book_audit add constraint FK8lcufuegfi49mwi9evabp20sg foreign key (rev) references revinfo (rev);
